### ISSUE TITLE
Support for component scripting (and checksums)

### ISSUE THREAD

**Issue by Skycoder42** [antony-jr/QInstallerBridge#1]
- [ ] Bug
- [x] Question
- [x] Suggestion
- [ ] Other (please describe):

QtIFW allows you to embbed javascript files for component scripting to for example create shortcuts or provide custom user interfaces. I don't see any of this (as well as other meta-stuff, like verifiying checksums) in your library. Are there any plans for supporting these additional features of QtIFW.

Note: I think at least verifying the checksums is a **must**. You can use `QCryptopgraphicHash` for that.

You can read more about component scripting here: https://doc.qt.io/qtinstallerframework/scripting.html

**Comment by antony-jr** [comment]
This is just a AutoUpdater with an elegant api and by my observations the installer framework does not operate on the component scripting on **updates** ( Only used on Installation ) so I thought I would totally avoid downloading the meta data and executing them , and the **checksum** seemed useless because the repo is in a web server and the checksum is the **SHA1 SUM** of the **meta.7z** archive and thus anyone can fake if by just replacing it with a different **SHA1** for the evil copy of **meta.7z** archive , So I thought I will just ignore them.

But If you think its needed then I will implement it in the next release !

**Comment by Skycoder42** [comment]
It depends on what you need. There are also the `.sha1` files used to verify the checksum for each 7z archive. They are used for 2 reasons: Integrity (make shure the download did not corrupt the file) and Load balancing. It is possible with QtIFW to have mirrors, and with the sha1sums one can use any mirror without trusting it, as you still get the checksum from the primary (and trusted) server. Thats why I think checksums of **both**, the meta.7z (if used) and the actual archives are relevant.

Regarding the component scripting, the documentation states:

> You might want to add custom operations after extracting the content, when copying files or patching file content, for example. You can create and add update operations to the installation from within a script using component::addOperation().

And special actions are executed on updates as well, depending on the kind of operation it is. One good example for this is the `FakeStopProcessForUpdate` operation. This is obviously something to be run on updates. A full list can be found here: https://doc.qt.io/qtinstallerframework/operations.html

**Comment by antony-jr** [comment]
okay got it , Thank you :heart:

**Comment by antony-jr** [comment]
its just **v0.0.1** so it will implemented on free time soon!

**Comment by antony-jr** [comment]
@Skycoder42 , I think you misunderstood this project , This is a full blown library , so when there is a mismatch in **SHA1** , it will emit a signal , this way you could do practically anything with C++ without the use of components scripts. like copying , warning the user , abort the update. You have to design the updater itself , which is childs play , because all you have to do is to connect the signals and slots , Why do Qt Installer Framework uses **Component Scripting** ? because it does not want the user to compile the installer all the time... So SHA1 Mismatch is automatically reported , I'm not reinventing the wheel with **Component Scripting** , its all upto the users wish. I think you get this , right! :heart:

**Correct me If I am wrong?**

**Comment by Skycoder42** [comment]
Scripts are not only about shasums. The primary goal of a component script is to perform additional operations needed when installing or update an application (e.g. set a registry key on windows). Of cause one can implement anything the scripts can do yourself, but that means a lot of extra work. When you create an installer, you create that script so the installer corretly sets up the system for you. On an update you need to do the same or at least similar actions.

So do you really want a developer to hard code update mechanics, that have already been written as a script, and are dependent on the platform into each program? Sure it's possible, but it's a bad idea and a bad design.

**Comment by antony-jr** [comment]
@Skycoder42 

**UPDATE**: Added Integrity Checks for All Packages and Downloadable Archives as of **v0.0.3**. https://github.com/antony-jr/QInstallerBridge/releases/tag/v0.0.3

Yet to add component scripting support.

**Comment by antony-jr** [comment]
@Skycoder42 I think component scripting is invalid here since this is an API and those who wish to use component script should use **your library.**

It works like this.... You design the updater ( Like Update in the Background or Dialog box ). When SHA1 Checksum is mismatched you handle the error with C++ (Because you design your own updater). This Project goal is to provide **maximum freedom** for the developer. That is , If he wants to design his own Updater from scratch and does not want to depend on Qt Maintanence tool. I think component scripting is not needed now. So I am closing this for now.

Thank You for your Time! 

> So do you really want a developer to hard code update mechanics, that have already been written as a script, and are dependent on the platform into each program? Sure it's possible, but it's a bad idea and a bad design.

Well you only have to write the component script for the installation which is manditory! But can code your own updater for your application in C++.

Component script only exist to cutomize your installer on wrong sha1,copy,delete,move and show message box. All of these can be easily done with C++ , Infact you can customize your updater to the core.

The Picture will get clear when my  you see my final product. Again Thank You for raising an issue here.
